name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.13

commands:
  elevators:
    description: Main elevators command
    usage: /elevators [reload]

permissions:
  elevators.reload:
    description: Allows reloading the plugin configuration
    default: op
